name: Deploy on LocalStack 

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Setup infrastructure using Serverless Framework
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          make install

      - name: Start LocalStack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          DNS_ADDRESS: 0
        run: |
          docker pull localstack/localstack-pro:latest
          # Start LocalStack in the background
          DEBUG=1 localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 15
          echo "Startup complete"

      - name: Run the application
        run: |
          make run
